[package]
name = "etk-asm"
version = "0.1.0"
authors = ["Sam Wilson <sam.wilson@mesh.xyz>", "lightclient <lightclient@protonmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[features]
cli = ["structopt", "etk-cli"]

[dependencies]
num_enum = "0.5.1"
hex = "0.4.2"
pest = "2.1"
pest_derive = "2.1"
sha3 = "0.9.1"
structopt = { optional = true, version = "0.3.21" }
etk-cli = { optional = true, path = "../etk-cli" }

[dev-dependencies]
assert_matches = "1.5.0"
hex-literal = "0.3.1"

[[bin]]
name = "eas"
required-features = ["cli"]
