[book]
authors = ["Sam Wilson"]
language = "en"
multilingual = false
src = "src"
title = "Ethereum Toolkit (ETK)"

[output.html]
git-repository-url = "https://github.com/quilt/etk"

[rust]
edition = "2018"
