[package]
name = "etk-analyze"
version = "0.1.0"
authors = ["Sam Wilson <sam.wilson@mesh.xyz>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[features]
cli = ["structopt", "etk-cli"]

[dependencies]
hex = "0.4.2"
etk-asm = { path = "../etk-asm" }
structopt = { optional = true, version = "0.3.21" }
etk-cli = { optional = true, path = "../etk-cli" }

[[bin]]
name = "disease"
required-features = ["cli"]
